@tool
extends EditorPlugin


func _get_plugin_name() -> String:
	return "Godot Charts"


func _enable_plugin() -> void:
	add_custom_type(
		"ChartDataSource",
		"Resource",
		preload("utils/chart_data_source.gd"),
		null
	)
	add_custom_type(
		"DictDataSource",
		"Resource",
		preload("utils/dict_data_source.gd"),
		null
	)
	add_custom_type(
		"CSVDataSource",
		"Resource",
		preload("utils/csv_data_source.gd"),
		null
	)
	add_custom_type(
		"StreamDataSource",
		"Resource",
		preload("utils/stream_data_source.gd"),
		null
	)
	add_custom_type(
		"GraphNetworkDataSource",
		"Resource",
		preload("utils/graph_network_data_source.gd"),
		null
	)
	add_custom_type(
		"ChartFrame3D",
		"Node3D",
		preload("charts/chart_frame_3d.gd"),
		null
	)
	add_custom_type(
		"PointChart3D",
		"Node3D",
		preload("charts/point_chart_3d.gd"),
		null
	)
	add_custom_type(
		"BarChart3D",
		"Node3D",
		preload("charts/bar_chart_3d.gd"),
		null
	)
	add_custom_type(
		"LineChart3D",
		"Node3D",
		preload("charts/line_chart_3d.gd"),
		null
	)
	add_custom_type(
		"ScatterChart3D",
		"Node3D",
		preload("charts/scatter_chart_3d.gd"),
		null
	)
	add_custom_type(
		"SurfaceChart3D",
		"Node3D",
		preload("charts/surface_chart_3d.gd"),
		null
	)
	add_custom_type(
		"HistogramChart3D",
		"Node3D",
		preload("charts/histogram_chart_3d.gd"),
		null
	)
	add_custom_type(
		"GraphNetworkChart3D",
		"Node3D",
		preload("charts/graph_network_chart_3d.gd"),
		null
	)
	add_custom_type(
		"CircuitChart3D",
		"Node3D",
		preload("circuits/circuit_chart_3d.gd"),
		null
	)
	add_custom_type(
		"VisualThemeTokens",
		"Resource",
		preload("assets/visual/visual_theme_tokens.gd"),
		null
	)
	add_custom_type(
		"VisualAssetGallery3D",
		"Node3D",
		preload("assets/visual/visual_asset_gallery_3d.gd"),
		null
	)
	add_custom_type(
		"WidgetPanel3D",
		"Node3D",
		preload("widgets/widget_panel_3d.gd"),
		null
	)
	add_custom_type(
		"WidgetRow3D",
		"Node3D",
		preload("widgets/widget_row_3d.gd"),
		null
	)
	add_custom_type(
		"WidgetColumn3D",
		"Node3D",
		preload("widgets/widget_column_3d.gd"),
		null
	)
	add_custom_type(
		"WidgetGrid3D",
		"Node3D",
		preload("widgets/widget_grid_3d.gd"),
		null
	)
	add_custom_type(
		"WidgetStack3D",
		"Node3D",
		preload("widgets/widget_stack_3d.gd"),
		null
	)
	add_custom_type(
		"WidgetThemeData3D",
		"Resource",
		preload("widgets/widget_theme_data_3d.gd"),
		null
	)
	add_custom_type(
		"WidgetControl3D",
		"Area3D",
		preload("widgets/widget_control_3d.gd"),
		null
	)
	add_custom_type(
		"WidgetLabel3D",
		"Node3D",
		preload("widgets/widget_label_3d.gd"),
		null
	)
	add_custom_type(
		"WidgetButton3D",
		"Area3D",
		preload("widgets/widget_button_3d.gd"),
		null
	)
	add_custom_type(
		"WidgetToggle3D",
		"Area3D",
		preload("widgets/widget_toggle_3d.gd"),
		null
	)
	add_custom_type(
		"WidgetSlider3D",
		"Area3D",
		preload("widgets/widget_slider_3d.gd"),
		null
	)
	add_custom_type(
		"WidgetListItem3D",
		"Area3D",
		preload("widgets/widget_list_item_3d.gd"),
		null
	)
	add_autoload_singleton(
		"WidgetFocusManager",
		"res://addons/godot-charts/widgets/widget_focus_manager.gd"
	)
	add_autoload_singleton(
		"WidgetThemeManager",
		"res://addons/godot-charts/widgets/widget_theme_manager_3d.gd"
	)


func _disable_plugin() -> void:
	remove_custom_type("ChartDataSource")
	remove_custom_type("DictDataSource")
	remove_custom_type("CSVDataSource")
	remove_custom_type("StreamDataSource")
	remove_custom_type("GraphNetworkDataSource")
	remove_custom_type("ChartFrame3D")
	remove_custom_type("PointChart3D")
	remove_custom_type("BarChart3D")
	remove_custom_type("LineChart3D")
	remove_custom_type("ScatterChart3D")
	remove_custom_type("SurfaceChart3D")
	remove_custom_type("HistogramChart3D")
	remove_custom_type("GraphNetworkChart3D")
	remove_custom_type("CircuitChart3D")
	remove_custom_type("VisualThemeTokens")
	remove_custom_type("VisualAssetGallery3D")
	remove_custom_type("WidgetPanel3D")
	remove_custom_type("WidgetRow3D")
	remove_custom_type("WidgetColumn3D")
	remove_custom_type("WidgetGrid3D")
	remove_custom_type("WidgetStack3D")
	remove_custom_type("WidgetThemeData3D")
	remove_custom_type("WidgetControl3D")
	remove_custom_type("WidgetLabel3D")
	remove_custom_type("WidgetButton3D")
	remove_custom_type("WidgetToggle3D")
	remove_custom_type("WidgetSlider3D")
	remove_autoload_singleton("WidgetFocusManager")
	remove_autoload_singleton("WidgetThemeManager")
	remove_custom_type("WidgetListItem3D")
